---
title: "Loan Data Prep"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  warning = FALSE, 
  message = FALSE)
library(tidyverse)
library(caret)
library(rsample)
```


## Data prep: loan data for #2 through #5


```{r}
library(tidyverse)
library(caret)
library(rsample)

# Load raw CSV file
loans_raw <- readr::read_csv("Loan_approval.csv")

# Helper functions
mode <- function(x, ...) {
  tx <- table(x)
  which(tx == max(tx)) %>% sort %>% `[`(., 1) %>% names
}
impute <- function(x, fun) {
  fval <- fun(x, na.rm = TRUE)
  y <- ifelse(is.na(x), fval, x)
  return(y)
}

# Prep statements
loans <- loans_raw %>% 
  select(-Loan_ID, -Gender) %>% 
  mutate(
    Married            = impute(Married, mode),
    Dependents         = impute(Dependents, mode),
    Education          = impute(Education, mode),
    Self_Employed      = impute(Self_Employed, mode),
    ApplicantIncome    = impute(ApplicantIncome, mean),
    CoapplicantIncome  = impute(CoapplicantIncome, mean),
    LoanAmount         = impute(LoanAmount, mean),
    Loan_Amount_Term   = impute(Loan_Amount_Term, mean),
    # TODO use mean or mode for Credit_History?
    # I think mode since it is a binary variable
    Credit_History     = impute(Credit_History, mode),
    Property_Area      = impute(Property_Area, mode),
    Loan_Status        = impute(Loan_Status, mode)  ) %>% 
  mutate(
    Total_Income = ApplicantIncome + CoapplicantIncome) %>% 
  select(-ApplicantIncome, -CoapplicantIncome) %>% 
  mutate(IncomeLoanRatio = Total_Income / LoanAmount) %>% 
  mutate_if(is.character, factor)

# Create dummyVars, *including* base levels!
dv <- dummyVars(~ ., data = loans, fullRank = FALSE)
loans_dv <- predict(dv, loans) %>% as.data.frame

# Split data: L is a binary vector
# so one can split loans or loans_dv the same way
set.seed(3)
S <- initial_split(loans, prop = .75, strata = Loan_Status)
L <- (1:nrow(loans)) %in% S$in_id

loans_train <- loans[L, ]
loans_test <- loans[!L, ]
loans_dv_train <- loans_dv[L, ]
loans_dv_test <- loans_dv[!L, ]

# Save Rds files for later use
write_rds(loans_train, 'data/loans_train.Rds')
write_rds(loans_test, 'data/loans_test.Rds')
write_rds(loans_dv_train, 'data/loans_dv_train.Rds')
write_rds(loans_dv_test, 'data/loans_dv_test.Rds')
```

