---
title: "Group 4 Final Project"
author: "Ajay Arora, Romerl Elizes, Jimmy Ng, Joshua Registe, Adam Rich"
date: "May 23, 2021"
output:
  rmdformats::readthedown:
    self_contained: yes
    thumbnails: yes
    lightbox: yes
    gallery: no
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  warning = FALSE, 
  message = FALSE,
  cache = TRUE)

packages <- c(
  'tidyverse', 
  'corrplot', 
  'palmerpenguins',
  'class',
  'kableExtra',
  'naniar',
  'DataExplorer',
  'caret',
  'tidymodels',
  'rsample',
  'themis',
  'randomForest',
  'car',
  'xgboost',
  'broom',
  'DBI',
  'RMySQL',
  'RJDBC'
)

for (pkg in packages) {
  suppressPackageStartupMessages(suppressWarnings(
    library(
      pkg, character.only = TRUE, 
      warn.conflicts = FALSE, quietly = TRUE)
  ))
}

# A ggplot2 function
defaulttheme <- theme(
  panel.background = element_blank(),
  panel.border = element_rect(color = "black", fill = NA))
```
 
## (Q1) Data Prep and Mitigation {.tabset .tabset-fade .tabset-pills} 

```{r}
colsqlstr <- "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = 'ny311';"

# placeholder for maxrows
maxrows = 100
cn <- dbConnect(drv      = RMySQL::MySQL(),
                username = "data622",
                password = "group4622",
                host     = "data622.c3alv39zxnhk.us-east-2.rds.amazonaws.com",
                port     = 3306,
                dbname   = "")

# I queried column names from ny311 so we can decide which variables to eliminate and use a for-loop to concatenate a string for the select statement we will use to download data.
colnms <- dbGetQuery(cn, colsqlstr)
colnmslist <- list(colnms$COLUMN_NAME)
str(colnmslist)


mainsqlstr <- paste("SELECT * FROM DATA622.ny311 order by rand() limit 0,",maxrows,";")
data2 <- dbGetQuery(cn, mainsqlstr)
data2

summary(data2)

#TO-DO - Most variables appear to be character variables. We have to convert them to their appropriate numerical, date, T/F, Y/N variables.

```

## (Q2) Random Forest {.tabset .tabset-fade .tabset-pills} 

TO-DO

## (Q3) Support Vector Machine {.tabset .tabset-fade .tabset-pills} 

TO-DO

## (Q4) Neural Network {.tabset .tabset-fade .tabset-pills} 

TO-DO

## (Q5) Model Performance and Selection {.tabset .tabset-fade .tabset-pills}

TO-DO